'''Perform operations with Pull Requests'''

import os
import time
from github import Github

def create_pull_request(repo_name, branch_name, resource_type, resource_name, resource_id):
    """
    Create a pull request for the imported resource.
    
    Args:
        repo_name: GitHub repository name (e.g., "username/repo")
        branch_name: Feature branch name
        resource_type: Type of imported resource
        resource_name: Name of the imported resource
        resource_id: ID of the imported resource
    
    Returns:
        PR URL if successful, None otherwise
    """
    # Get GitHub token from environment variable
    github_token = os.environ.get('GITHUB_TOKEN')
    if not github_token:
        return None, "GitHub token not found. Set GITHUB_TOKEN environment variable."

    try:
        # Create GitHub client
        g = Github(github_token)
        github_repo = g.get_repo(repo_name)

        # Create PR template
        pr_title = f"Import {resource_type}: {resource_name}"

        pr_body = f"""## Resource Import Details

**Resource Type:** {resource_type}
**Resource ID:** {resource_id}
**Local Name:** {resource_name}

**Imported By:** @{g.get_user().login}
**Import Date:** {time.strftime("%Y-%m-%d %H:%M UTC")}
**Reason for Import:** Bringing existing resource under Pulumi management

**Configuration Details:**
- Resource is imported with its current configuration
- No changes to the existing resource were made

---
*This PR was automatically generated by Pulumi Resource Importer*
"""

        # Create the pull request
        pr = github_repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base="main"
        )

        return pr.html_url, None
    except Exception as e: # pylint: disable=broad-exception-caught
        return None, f"Error creating pull request: {e}"
